# Generated by Django 3.0.6 on 2020-05-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20200516_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='back_image',
            field=models.ImageField(blank=True, default='def_back.jpg', upload_to='user-profile-image'),
        ),
    ]
