# Generated by Django 3.0.3 on 2020-06-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_useraddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
    ]
