# Generated by Django 3.0.3 on 2020-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('opening_time', models.CharField(max_length=120)),
                ('average_delivery', models.CharField(max_length=120)),
            ],
        ),
    ]
