# Generated by Django 3.0.3 on 2020-05-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_auto_20200506_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='image',
            field=models.ImageField(blank=True, default='smth', upload_to='book-image'),
        ),
    ]
