# Generated by Django 3.0.3 on 2020-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0004_auto_20200507_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='food',
        ),
        migrations.AddField(
            model_name='foods',
            name='restaurant',
            field=models.ManyToManyField(related_name='food', to='Restaurants.Restaurants'),
        ),
    ]
