# Generated by Django 3.0.3 on 2020-05-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0006_auto_20200508_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(blank=True, default='smth', upload_to='rest-image'),
        ),
    ]
