# Generated by Django 3.0.3 on 2020-05-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0007_auto_20200508_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='image',
            field=models.ImageField(blank=True, default='smth', upload_to='food-image'),
        ),
    ]
