# Generated by Django 3.0.3 on 2020-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0010_auto_20200509_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
