# Generated by Django 3.0.3 on 2020-05-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0011_auto_20200510_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
