# Generated by Django 3.0.3 on 2020-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_food_category'),
        ('Restaurants', '0012_auto_20200510_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='food', to='Category.Food_Category'),
        ),
    ]
