# Generated by Django 3.0.3 on 2020-05-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0014_auto_20200529_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='food_category',
        ),
    ]
