# Generated by Django 3.0.3 on 2020-05-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_remove_food_category_food'),
        ('Restaurants', '0015_remove_foods_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='food_category',
            field=models.ManyToManyField(blank=True, related_name='food', to='Category.Food_Category'),
        ),
    ]
