# Generated by Django 3.0.3 on 2020-05-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0016_foods_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='food_category',
        ),
    ]
