# Generated by Django 3.0.3 on 2020-05-30 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_remove_food_category_food'),
        ('Restaurants', '0017_remove_foods_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Category.Food_Category'),
        ),
    ]
