# Generated by Django 3.0.3 on 2020-05-31 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0007_food_category_restaurant'),
        ('Restaurants', '0018_foods_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='Category.Food_Category'),
        ),
    ]
