# Generated by Django 3.0.3 on 2020-05-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0008_remove_food_category_restaurant'),
        ('Restaurants', '0019_auto_20200531_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='food_category',
            field=models.ManyToManyField(blank=True, related_name='restaurant', to='Category.Food_Category'),
        ),
    ]
