# Generated by Django 3.0.3 on 2020-05-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0020_restaurants_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='food_category',
        ),
    ]
