# Generated by Django 3.0.3 on 2020-05-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0008_remove_food_category_restaurant'),
        ('Restaurants', '0021_remove_restaurants_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='food_category',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='food_category',
            field=models.ManyToManyField(blank=True, related_name='restaurant', to='Category.Food_Category'),
        ),
    ]
