# Generated by Django 3.0.3 on 2020-05-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0008_remove_food_category_restaurant'),
        ('Restaurants', '0022_auto_20200531_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='food_category',
        ),
        migrations.AddField(
            model_name='foods',
            name='food_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='Category.Food_Category'),
        ),
    ]
