# Generated by Django 3.0.3 on 2020-05-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0023_auto_20200531_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='food_category',
        ),
    ]
