# Generated by Django 3.0.3 on 2020-05-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0008_remove_food_category_restaurant'),
        ('Restaurants', '0024_remove_foods_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='food_category',
            field=models.ManyToManyField(blank=True, related_name='food_category', to='Category.Food_Category'),
        ),
    ]
