# Generated by Django 3.0.3 on 2020-06-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0025_foods_food_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants',
            options={'verbose_name_plural': 'Restaurants'},
        ),
    ]
