# Generated by Django 3.0.3 on 2020-06-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0026_auto_20200603_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name_plural': 'Foods'},
        ),
    ]
