# Generated by Django 3.0.3 on 2020-06-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0027_auto_20200603_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants',
            options={'ordering': ['name'], 'verbose_name_plural': 'Restaurants'},
        ),
    ]
