# Generated by Django 3.0.3 on 2020-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurants', '0003_restaurants_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('restaurant', models.ManyToManyField(to='Restaurants.Restaurants')),
            ],
        ),
    ]
