# Generated by Django 3.0.3 on 2020-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_foods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
