# Generated by Django 3.0.3 on 2020-05-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_auto_20200507_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='slug',
        ),
    ]
