# Generated by Django 3.0.3 on 2020-05-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0006_foods_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
