# Generated by Django 3.0.3 on 2020-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='smth', upload_to='pictures/%Y/%m/'),
        ),
    ]
