# Generated by Django 3.0.3 on 2020-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0015_remove_foods_food_category'),
        ('Category', '0004_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_category',
            name='food',
            field=models.ManyToManyField(blank=True, related_name='food', to='Restaurants.Foods'),
        ),
    ]
