# Generated by Django 3.0.3 on 2020-05-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0005_food_category_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_category',
            name='food',
        ),
    ]
