# Generated by Django 3.0.3 on 2020-05-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0007_food_category_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_category',
            name='restaurant',
        ),
    ]
