# Generated by Django 3.0.3 on 2020-06-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_address',
        ),
    ]
